[toolchain]
# Specifying an explicit Solana version that's compatible with Anchor 0.27.0
solana = "1.14.17"
package_manager = "yarn"
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
autotp = "FqzkXZdwYjurnUKetJCAvaUw5WAqbwzU6gZEwydeEfqS"

[programs.devnet]
autotp = "FqzkXZdwYjurnUKetJCAvaUw5WAqbwzU6gZEwydeEfqS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
build = "anchor build"
idl = "anchor idl parse -f programs/autotp/src/lib.rs -o target/idl/autotp.json"
copy-idl = "mkdir -p ../src/idl && cp target/idl/autotp.json ../src/idl/"
build-all = "anchor run build && anchor run idl && anchor run copy-idl"

[build]
skip-build = false
